use_frameworks!

platform :ios, '8.0'

target 'HTCollectionFallLayout_Example' do
  pod 'HTCollectionFallLayout', :path => '../'

  target 'HTCollectionFallLayout_Tests' do
    inherit! :search_paths

    
  end
end
